name: Publish Website

on:
  push:
    branches:
      - production


jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: nonprof.sagirisdev.com
        remote-user: dh_9u8uyj
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /home/dh_9u8uyj/nonprof.sagirisdev.com/wp-content/themes/spiritwestuc/
